### PR TITLE
Map rag model to device in eval rag script

### PR DESCRIPTION
**Pull request by sagorbrur**
Hi,
According to our discussion on issue #73 , here I have added device mapping in `eval_rag.py`.
I have tested and no device mismatch error raising now.

Please have a look and merge if everything is okay. 

Thanks and regards

### CODE REVIEW

**Review by shamanez — APPROVED** [review]
looks good to me!

**Review by shamanez — CHANGES_REQUESTED** [review]
Maybe let's add this code snippet here: 

Also let's add a comment above this line
`rag_model.attach_pre_trained_peft_layers(retriever_peft_model_path, generator_peft_model_path, device)`

Something like -  "we only wrap this with PEFT layers if there are any ... :


https://github.com/arcee-ai/DALM/blob/a8476405dbc92a6acb0784094c73f70044843354/dalm/models/rag_e2e_base_model.py#L135

**Comment by metric-space** [comment]
Hey @sagorbrur , thank you for the PR

I think while the code in general looks good, it may be more optimal to place the code here:  https://github.com/arcee-ai/DALM/blob/a8476405dbc92a6acb0784094c73f70044843354/dalm/models/rag_e2e_base_model.py#L113

once that's in, should be good to merge in

**Comment by sagorbrur** [comment]
HI @shamanez ,


> @sagorbrur Maybe let's add this code snippet here:
> 
> Also let's add a comment above this line `rag_model.attach_pre_trained_peft_layers(retriever_peft_model_path, generator_peft_model_path, device)`
> 
> Something like - "we only wrap this with PEFT layers if there are any ... :
> 
> Thanks a lot :)
> 
> https://github.com/arcee-ai/DALM/blob/a8476405dbc92a6acb0784094c73f70044843354/dalm/models/rag_e2e_base_model.py#L135

The line you refer I am a little bit confused about where to put it. 
It would be great if you clarify a bit. 

regards

**Comment by metric-space** [comment]
Hey @sagorbrur is the comment part unclear or is the request to move the code to the specified location unclear?

**Comment by sagorbrur** [comment]
> Hey @sagorbrur is the comment part unclear or is the request to move the code to the specified location unclear?

Hi @metric-space ,
I am unclear about moving the part to the specified location. 
I am requesting maintainers to apply that. 
Please if possible add the modification in desired location. 

Kind regards

**Pull request merged**
